### TEST REGISTER
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "phone": "08104068728",
    "password": "p1ssw4rd",
    "first_name": "Fola",
    "last_name": "Ajibola",
    "pin": "1100",
    "email" : "fola.ajibola@example.com"
}

# {
#     "phone": "09015780030",
#     "password": "securePass123",
#     "first_name": "Mojola",
#     "last_name": "Ajibola",
#     "pin": "2910",
#     "email" : "mojola.ajibola@example.com"
# }


### LOGIN API
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "phone": "09015780030",
    "password": "securePass123",
    "pin": "2910" 
}
###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "phone": "08104068728",
    "password": "p1ssw4rd",
    "pin": "1100" 
}



###GET BALANCE
GET http://localhost:8080/api/v1/wallets/balance
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODU2NjY3MiwibmJmIjoxNzY4NTY1NzcyLCJpYXQiOjE3Njg1NjU3NzIsImp0aSI6ImY5MzBiNTg5LTZlNzUtNDJhZS1hNTg0LTkxMjdlZWRjOTkzZiJ9.wl_HIv_yLNuQEH0rHd0N5-76a1C6DDpBNmAK3pKmD04LT-b23I2ZSnowHzU99Nc8_EhLrBDGgHlJQLLqLIPqIw

### GET USER PROFILE
GET http://localhost:8080/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjY3NTZkMjQtZmJhZC00YWE2LTk5NGUtZmY4YjVlYjBlM2YzIiwicGhvbmUiOiIwODEwNDA2ODcyOCIsImV4cCI6MTc2ODQ5NjM5MSwibmJmIjoxNzY4NDk1NDkxLCJpYXQiOjE3Njg0OTU0OTEsImp0aSI6IjQ4MjA0ZGRhLWI3NzMtNDllNC1hYWEzLWVkNjc1NzNmNzlmOSJ9.MCKebzyi9sDwj1Xug0cUletxb8BMDX1tRmldwUozjNxOA1RuOga1W_XSKMUcGaLnTYAWD4zrbJIoFaAEb47yog

###
GET http://localhost:8080/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODQ5NjM1NiwibmJmIjoxNzY4NDk1NDU2LCJpYXQiOjE3Njg0OTU0NTYsImp0aSI6ImNkYTU2OWJkLWRkODItNDgyYS1iNzRhLTVmNzRlM2UwZWJiZCJ9._7LaptXv9NBJjLh2rG8_kX71y_5e1spW5BzOk0pztUDDme5zGdB8mVRwisgX50H6hZrYrgtALKtd1L_tSG01hw


### CHECK BALANCE
GET http://localhost:8080/api/v1/wallets/balance
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODQ5NjM1NiwibmJmIjoxNzY4NDk1NDU2LCJpYXQiOjE3Njg0OTU0NTYsImp0aSI6ImNkYTU2OWJkLWRkODItNDgyYS1iNzRhLTVmNzRlM2UwZWJiZCJ9._7LaptXv9NBJjLh2rG8_kX71y_5e1spW5BzOk0pztUDDme5zGdB8mVRwisgX50H6hZrYrgtALKtd1L_tSG01hw


### TRANSFER
POST http://localhost:8080/api/v1/transactions/transfer
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODQ5NjM1NiwibmJmIjoxNzY4NDk1NDU2LCJpYXQiOjE3Njg0OTU0NTYsImp0aSI6ImNkYTU2OWJkLWRkODItNDgyYS1iNzRhLTVmNzRlM2UwZWJiZCJ9._7LaptXv9NBJjLh2rG8_kX71y_5e1spW5BzOk0pztUDDme5zGdB8mVRwisgX50H6hZrYrgtALKtd1L_tSG01hw
Idempotency-Key : 83947ab1-a735-43d3-88b0-11d52d48fng2
Content-Type: application/json

{
    "wallet_id": "83947ab1-a735-43d3-88b0-11d52d48fda8",
    "amount": 75000,
    "description": "Limit Test",
    "pin": "2910"
}

###
POST http://localhost:8080/api/v1/transactions/transfer
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODQ3MDgzMSwibmJmIjoxNzY4NDY5OTMxLCJpYXQiOjE3Njg0Njk5MzEsImp0aSI6IjRjMzJkNmU2LWY4OTQtNDY1ZS1iNGFiLTY3MTFmM2JlNmRhOCJ9.6ByPkoaFXz4aum640LoMjIJJ6JkyNP98uaBGHpO6vk_tm_Amx9Uy2GlciMOhaLZkFKlLl29SkU8Korg46ng4wQ
Idempotency-Key : 550e8400-e29b-41d4-a716-446655440011
Content-Type: application/json

{
    "wallet_id": "83947ab1-a735-43d3-88b0-11d52d48fda8",
    "amount": 75000,
    "description": "Test Idempotency",
    "pin": "2910"
}
###
GET http://localhost:8080/api/v1/limits
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjY3NTZkMjQtZmJhZC00YWE2LTk5NGUtZmY4YjVlYjBlM2YzIiwicGhvbmUiOiIwODEwNDA2ODcyOCIsImV4cCI6MTc2ODU3MjE5NiwibmJmIjoxNzY4NTcxMjk2LCJpYXQiOjE3Njg1NzEyOTYsImp0aSI6IjcxYTJlMTk0LWJmYzEtNDYxOC1iMzhhLWYzNTg1ZTI5NmY0NSJ9.YwYXcjY-hDkwz1_XeYNmHOvwdFOJRUSCKQPaPk8SECYgBN4QNzxF19BNRe_cyU-1KexjwbM5w2vQLeMQzmoSGA