### TEST LOGIN
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
    "phone": "08104068728",
    "password": "p1ssw4rd",
    "first_name": "Fola",
    "last_name": "Ajibola",
    "pin": "1100",
    "email" : "fola.ajibola@example.com"
}

# {
#     "phone": "09015780030",
#     "password": "securePass123",
#     "first_name": "Mojola",
#     "last_name": "Ajibola",
#     "pin": "2910",
#     "email" : "mojola.ajibola@example.com"
# }


### LOGIN API
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "phone": "09015780030",
    "password": "securePass123",
    "pin": "2910" 
}
###
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "phone": "08104068728",
    "password": "p1ssw4rd",
    "pin": "1100" 
}



###GET BALANCE
GET http://localhost:8080/api/v1/wallets/balance
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjY3NTZkMjQtZmJhZC00YWE2LTk5NGUtZmY4YjVlYjBlM2YzIiwicGhvbmUiOiIwODEwNDA2ODcyOCIsImV4cCI6MTc2ODQ3MDgxMCwibmJmIjoxNzY4NDY5OTEwLCJpYXQiOjE3Njg0Njk5MTAsImp0aSI6ImE3NzA4MWY3LWRhYTYtNGE3My05NjM0LTY0MGFlYmQwNTBmYiJ9.amBJ779WubJdBerllywuyTVK0ArcftglQ9IVhUL3EQNsKmflezQhwJhzOOqBmiiMRtI1q8fYg4fyGYlbKxk6Ug

### GET USER PROFILE
GET http://localhost:8080/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODM5ODAwNywibmJmIjoxNzY4Mzk3MTA3LCJpYXQiOjE3NjgzOTcxMDcsImp0aSI6Ijc0ZTgyMzE1LWUxNzMtNDZmMy1iMTc0LTdkOTNiODdmMTFmMyJ9.aIlwv3PSjfl-Zyko5l85IBn26zWK_xunwryc76Tb26PYiCSMlVsjC5DUm5iOlBIEImQoE23KlLft1SbnUXAJoQ

###
GET http://localhost:8080/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODQ3MDgzMSwibmJmIjoxNzY4NDY5OTMxLCJpYXQiOjE3Njg0Njk5MzEsImp0aSI6IjRjMzJkNmU2LWY4OTQtNDY1ZS1iNGFiLTY3MTFmM2JlNmRhOCJ9.6ByPkoaFXz4aum640LoMjIJJ6JkyNP98uaBGHpO6vk_tm_Amx9Uy2GlciMOhaLZkFKlLl29SkU8Korg46ng4wQ


### CHECK BALANCE
GET http://localhost:8080/api/v1/wallets/balance
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODQ3MDgzMSwibmJmIjoxNzY4NDY5OTMxLCJpYXQiOjE3Njg0Njk5MzEsImp0aSI6IjRjMzJkNmU2LWY4OTQtNDY1ZS1iNGFiLTY3MTFmM2JlNmRhOCJ9.6ByPkoaFXz4aum640LoMjIJJ6JkyNP98uaBGHpO6vk_tm_Amx9Uy2GlciMOhaLZkFKlLl29SkU8Korg46ng4wQ


### TRANSFER
POST http://localhost:8080/api/v1/transactions/transfer
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODQ3MDgzMSwibmJmIjoxNzY4NDY5OTMxLCJpYXQiOjE3Njg0Njk5MzEsImp0aSI6IjRjMzJkNmU2LWY4OTQtNDY1ZS1iNGFiLTY3MTFmM2JlNmRhOCJ9.6ByPkoaFXz4aum640LoMjIJJ6JkyNP98uaBGHpO6vk_tm_Amx9Uy2GlciMOhaLZkFKlLl29SkU8Korg46ng4wQ
Idempotency-Key : 550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
    "wallet_id": "83947ab1-a735-43d3-88b0-11d52d48fda8",
    "amount": 10000,
    "description": "Test Idempotency",
    "pin": "2910"
}

###
POST http://localhost:8080/api/v1/transactions/transfer
Authorization: Bearer eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiM2YwNjNkMDMtY2E2Yi00OGJhLWI1Y2YtYmEyNDg0YmJkYmM2IiwicGhvbmUiOiIwOTAxNTc4MDAzMCIsImV4cCI6MTc2ODQ3MDgzMSwibmJmIjoxNzY4NDY5OTMxLCJpYXQiOjE3Njg0Njk5MzEsImp0aSI6IjRjMzJkNmU2LWY4OTQtNDY1ZS1iNGFiLTY3MTFmM2JlNmRhOCJ9.6ByPkoaFXz4aum640LoMjIJJ6JkyNP98uaBGHpO6vk_tm_Amx9Uy2GlciMOhaLZkFKlLl29SkU8Korg46ng4wQ
Idempotency-Key : 550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json

{
    "wallet_id": "83947ab1-a735-43d3-88b0-11d52d48fda8",
    "amount": 10000,
    "description": "Test Idempotency",
    "pin": "2910"
}
